name: Update GitHub Metrics

on:
  schedule:
    - cron: "30 4 * * *" # daily at 04:30 UTC
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics-light:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/metrics-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          config_timezone: America/Vancouver
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  metrics-dark:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/metrics-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          config_timezone: America/Vancouver
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_display: "dark"
